migrated to ui components and python sdk
corbado/example-passkeys-python-django pull request #1
Opened 2024-05-31 07:42 UTC by alexbalakirev

2024-06-06 11:20 UTC, vincentdelitz requested changes
- [x] Please add a `.env.example`file with the right placeholders
- [x] Fix security updates
- [x] Please add passkey-list component
- [x] Same docker issue like on the other 2 repositories:
<img width="955" alt="image" src="https://github.com/corbado/example-passkeys-python-django/assets/18458907/2432f465-17e8-4e47-9e4c-044a125b4636">

2024-06-06 11:20 UTC, vincentdelitz commented on passkeys_demo/templates/index.html
> +      href="https://unpkg.com/@corbado/web-js@2.6.0/dist/bundle/index.css"
use version 2.8.0

2024-06-07 16:17 UTC, alexbalakirev commented on passkeys_demo/templates/index.html
> +      href="https://unpkg.com/@corbado/web-js@2.6.0/dist/bundle/index.css"
Done

2024-06-13 16:22 UTC, vincentdelitz commented
@alexbalakirev habe es lokal mit docker-compose gestartet und kann einen Account + Passkey anlegen. Allerdings, werde ich nicht richtig auf die /profile Seite verlinkt, sondern bleibe nach kurzem Site-Reload auf der aktuellen Seite. Funktioniert das bei dir?

2024-06-13 16:32 UTC, alexbalakirev commented
> @alexbalakirev habe es lokal mit docker-compose gestartet und kann einen Account + Passkey anlegen. Allerdings, werde ich nicht richtig auf die /profile Seite verlinkt, sondern bleibe nach kurzem Site-Reload auf der aktuellen Seite. Funktioniert das bei dir?

Did it work in the old version?

2024-06-13 16:43 UTC, vincentdelitz commented
> > @alexbalakirev habe es lokal mit docker-compose gestartet und kann einen Account + Passkey anlegen. Allerdings, werde ich nicht richtig auf die /profile Seite verlinkt, sondern bleibe nach kurzem Site-Reload auf der aktuellen Seite. Funktioniert das bei dir?
> 
> Did it work in the old version?

What do you mean by old version? The one before last Friday or the one with web component and no dedicated SDK?

2024-06-13 16:45 UTC, alexbalakirev commented
> > > @alexbalakirev habe es lokal mit docker-compose gestartet und kann einen Account + Passkey anlegen. Allerdings, werde ich nicht richtig auf die /profile Seite verlinkt, sondern bleibe nach kurzem Site-Reload auf der aktuellen Seite. Funktioniert das bei dir?
> > 
> > 
> > Did it work in the old version?
> 
> What do you mean by old version? The one before last Friday or the one with web component and no dedicated SDK?

The version on the main brach without any changes.

2024-06-13 18:20 UTC, vincentdelitz commented
> > > > @alexbalakirev habe es lokal mit docker-compose gestartet und kann einen Account + Passkey anlegen. Allerdings, werde ich nicht richtig auf die /profile Seite verlinkt, sondern bleibe nach kurzem Site-Reload auf der aktuellen Seite. Funktioniert das bei dir?
> > > 
> > > 
> > > Did it work in the old version?
> > 
> > 
> > What do you mean by old version? The one before last Friday or the one with web component and no dedicated SDK?
> 
> The version on the main brach without any changes.

Nope main branch doesn't work either - same behavior.

2024-06-14 11:30 UTC, alexbalakirev commented
Issues resolved

2024-06-24 12:35 UTC, merged